[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[lib]
bench = false


[dependencies]
regex = "1.10.2"
itertools = "0.12.0"
num = "0.4.1" 
euclid = "0.22.9"
bmp = "0.5.0"
range-ext = "0.3.0"
eqsolver = "0.1.2"
nalgebra = "0.32.3"
petgraph = "0.6.4"

